name: 'Play with auto-download .NETFramework'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  configuration: Release

jobs:
  build-w:
    name: .NET 5
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Run on Ubuntu
      working-directory: ConsoleApp2
      run: dotnet run -c ${{ env.configuration }}

  build-u:
    name: .NET Core 3.1 
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Build on Ubuntu
      working-directory: ConsoleApp2
      run: dotnet build -c ${{ env.configuration }}
